/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401cc.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	 RCC->AHB1ENR |=(1<<0);

	 GPIOA->MODER &= ~(3<<0);
	 GPIOA->MODER |= (1<<0);
	 GPIOA->PUPDR |= (1<<0);
		/* Loop forever */
	while(1)
	{


		GPIOA->ODR ^=(1<<0);
		for(int i=0; i<100000;i++);
//	GPIOA->ODR |=(1<<0);

	}

}
