/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401cc.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	  /* Enable the AHB clock all GPIO Port A */
	  RCC->AHB1ENR |= (1<<0);
	  /* set  Port A 1 pin as input mode */
	  GPIOA->MODER &= ~(3<<2);
	  /* set  Port A 0 pin as output mode */
	  GPIOA->MODER |= (1<<0);
	  /* set Port A pin 1 as PULLUP mode */
	  GPIOA->PUPDR &= ~(3<<2);
	  GPIOA->PUPDR |= (1<<2);

	  uint8_t data =0;

		while(1)
		{
			   if((GPIOA->IDR & (1<<1))== 0)
			   {
				   data =0;

				   GPIOA->ODR &= ~(1<<0);
			   }
			   else {
				   data = 1;
				   GPIOA->ODR |= (1<<0);
			   }
		}

}
/* Reference: https://embetronicx.com/tutorials/microcontrollers/stm32/stm32-gpio-tutorial/ */


/* 						NOTE
 *
 * Here the Controller wants to continously check the button status
 *
 * That can be solved using external interrupt
 *
 * when the button pressed the function will be executed
 *
 * */
